Repository istio/community, pull requests merged in 2019-10, with the labels that each got.

#222 Changed Code of Conduct, added ref. to steering on index
  CONTRIBUTING.md
  README.md
  STEERING-COMMITTEE.md
Labels: cla: yes, size/S

#223 Update leads.
  WORKING-GROUPS.md
Labels: cla: yes, size/XS

#227 Reflect lead updates.
  WORKING-GROUPS.md
Labels: cla: yes, size/M

#229 Update to latest container.
  Makefile
Labels: cla: yes, size/XS
