Repository istio/community, pull requests merged in 2019-07, with the labels that each got.

#200 Add IBM.
  EARLY-DISCLOSURE.md
Labels: size/XS

#202 Update EARLY-DISCLOSURE.md
  EARLY-DISCLOSURE.md
Labels: size/XS

#204 Add UX YouTube link
  WORKING-GROUPS.md
Labels: size/XS

#205 Update roles for members and maintainers.
  ROLES.md
Labels: size/S

#206 Migrate from Mergify/CircleCi to Tide/Prow
  .circleci/config.yml
  .mergify.yml
  Makefile
  README.md
  prow/community-lint.sh
Labels: size/M

#208 Change @sdake affiliation
  WORKING-GROUPS.md
Labels: cla: yes, size/XS

#207 Don't need this anymore, given eng.istio.io/maintainers
  MAINTAINERS.md
  README.md
Labels: cla: yes, size/M
