Repository istio/community, pull requests merged in 2020-09, with the labels that each got.

#415 Add @e-blackwelder to developers.yaml
  org/developers.yaml
Labels: cla: yes, ok-to-test, size/XS

#413 Add costinm and howardjohn as Security maintainers
  org/teams.yaml
Labels: cla: yes, size/XS

#414 Add chaodaiG as developer
  org/developers.yaml
Labels: cla: yes, ok-to-test, size/XS

#402 Updated members.yaml
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#418 Create a T&R Operations group to simply CODEOWNERS in test-infra
  org/teams.yaml
Labels: cla: yes, size/XS

#419 Add jtrbs as developers
  org/developers.yaml
Labels: cla: yes, ok-to-test, size/XS

#393 Add nikita15p to istio org
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#420 added jwebb49 to members.yaml
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#425 Add Neeraj Poddar's nomination for Steering Committee elections
  steering/elections/2020/nrjpoddar.md
Labels: cla: yes, size/S

#422 add hacktron95 as a member
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#426 Add instruction to add names in alphabetical order.
  org/README.md
  org/admins.yaml
  org/config_test.go
  org/developers.yaml
  org/gen.go
  org/members.yaml
  org/teams.yaml
Labels: cla: yes, size/M

#429 Add Jimmy Song's nomination for Steering Committee elections
  steering/elections/2020/jimmysong.md
Labels: cla: yes, ok-to-test, size/S

#430 Clarification of time
  steering/elections/2020/README.md
Labels: cla: yes, size/XS

#434 added Jason Webb bio
  steering/elections/2020/jasonwebb.md
Labels: cla: yes, ok-to-test, size/XS

#431 Nominate @ZackButcher for steering committee
  steering/elections/2020/zackbutcher.md
Labels: cla: yes, size/S

#433 Nomination: Suresh Visvanathan
  steering/elections/2020/sureshvis.md
Labels: cla: yes, size/S, steering-elections

#436 Add 2020 nominees
  steering/elections/2020/README.md
Labels: cla: yes, size/XS

#437 Add exception voters to 2020 voters list
  steering/elections/2020/VOTERS.md
Labels: cla: yes, size/XS

#438 Update zackbutcher.md to add some list markdown
  steering/elections/2020/zackbutcher.md
Labels: cla: yes, size/XS

#412 add stevenctl to networking
  org/teams.yaml
Labels: cla: yes, size/XS

#440 Add Mariam John to Test and Releaes Maintainers
  org/teams.yaml
Labels: cla: yes, size/XS

#439 Add sureshvis to members list
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#435 Add zhihanz to developers
  org/developers.yaml
Labels: cla: yes, ok-to-test, size/XS

#417 Clean up feature level requirements to only contain content we want to require
  FEATURE-LIFECYCLE-CHECKLIST.md
Labels: cla: yes, size/S

#443 Fix Neeraj's LinkedIn link
  steering/elections/2020/nrjpoddar.md
Labels: cla: yes, size/XS

#444 Add chizhg as developer
  org/developers.yaml
Labels: cla: yes, ok-to-test, size/XS

#446 Fix dead link
  ROLES.md
Labels: cla: yes, size/XS

#448 Add jtrbs as voter
  steering/elections/2020/VOTERS.md
Labels: cla: yes, ok-to-test, size/XS

#447 Move sample janedoe out of list of candidates
  steering/elections/2020/README.md
  steering/elections/sample-janedoe.md
Labels: cla: yes, size/XS

#451 add lyzhang1999 as a member
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#457 Update who sent the e-mail
  steering/elections/2020/README.md
Labels: cla: yes, size/XS

#455 Adding luckoseabraham as a member.
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#458 Add exception for lyzhang1999
  steering/elections/2020/VOTERS.md
Labels: cla: yes, size/XS

#452 Update teams.yaml for davidhauck
  org/teams.yaml
Labels: cla: yes, size/XS

#462 Update sample-janedoe.md
  steering/elections/sample-janedoe.md
Labels: cla: yes, size/XS

#464 Add steering election results for 2020
  steering/README.md
Labels: cla: yes, size/XS

#463 Add Solo.io to early disclosure
  EARLY-DISCLOSURE.md
Labels: cla: yes, size/XS
