Repository istio/community, pull requests merged in 2020-06, with the labels that each got.

#332 Remove sdake from docs
  org/istio.yaml
Labels: cla: yes, size/XS

#333 Add shakti-das to the Istio org
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#334 Add nschhina to Org and Developers
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#336 add stevenctl to Test and Release Maintainers
  org/istio.yaml
Labels: cla: yes, size/XS

#335 Rename gorda
  org/istio.yaml
Labels: cla: yes, size/XS

#338 Add knight42 to Org and Developers
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#339 Add Lei to security maintainers.
  org/istio.yaml
Labels: cla: yes, size/XS

#340 Add Cynthia Coan to for membership
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#341 add Shikugawa as member of istio
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#342 add heatherzheng as member of istio
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#344 Add joeyb to the Istio org
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#345 Move sync from makefile to script
  Makefile
  prow/sync-org.sh
Labels: cla: yes, size/S

#346 remove performance WG
  WORKING-GROUPS.md
Labels: cla: yes, size/XS

#347 update "monsteredc" to members tag
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#349 add to williamaronli istio member
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#353 Add ZhengzheYang to the org
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#351 add aronli as a member
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#352 Add S-Chan to Istio members
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#354 Fix work dir for sync
  prow/sync-org.sh
Labels: cla: yes, size/XS

#355 Added nrjpoddar to TOC
  TECH-OVERSIGHT-COMMITTEE.md
  org/istio.yaml
Labels: cla: yes, size/S

#356 Fix typo
  org/istio.yaml
Labels: cla: yes, size/XS

#359 update list of members in early disclosure list
  EARLY-DISCLOSURE.md
Labels: cla: yes, size/XS

#360 Update istio.yaml
  org/istio.yaml
Labels: cla: yes, size/XS
