Repository istio/community, pull requests merged in 2020-05, with the labels that each got.

#318 Add Shweta Singh for membership
  org/istio.yaml
Labels: cla: yes, size/XS

#320 Clarify minimum bar for feature stages listing
  FEATURE-LIFECYCLE-CHECKLIST.md
  FEATURE-LIFECYCLE.md
Labels: cla: yes, size/S

#321 Clarify working group lead requirements
  WORKING-GROUP-PROCESSES.md
Labels: cla: yes, size/XS

#324 Add Shamsher Ansari to member and developer list
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#325 Add member
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#317 Update youtube poc
  ADMINS-FOR-ISTIO.md
Labels: cla: yes, size/XS

#315 add kevin21th to org
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#328 Add bcheung to org and developers
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#329 Ignore links that fail due to '429 Too Many Requests'.
  prow/community-lint.sh
Labels: cla: yes, size/XS
