Repository istio/community, pull requests merged in 2020-07, with the labels that each got.

#358 Add domgoer to Org and Developers
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#362 Update ADMINS-FOR-ISTIO.md
  ADMINS-FOR-ISTIO.md
Labels: cla: yes, size/XS

#364 Add release 1.7 managers
  org/istio.yaml
Labels: cla: yes, size/S

#365 Add bison to Istio GitHub org
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#367 add xulingqing as member
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#369 Adjust membership for @clarketm
  org/istio.yaml
Labels: cla: yes, size/XS

#366 Add qwertyuiop8888 to org and developers
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#368 Add tbarrella as a member
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#370 Update WG Leads table
  WORKING-GROUPS.md
Labels: cla: yes, size/XS

#373 Move community meeting from 11am to 10am.
  README.md
Labels: cla: yes, size/XS

#372 add yingzhuivy to istio members
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#374 Add xulingqing as member
  org/istio.yaml
Labels: cla: yes, size/XS

#375 add juswei as a member
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#377 remove @ayj from the list of Istio maintainers
  WORKING-GROUPS.md
  org/istio.yaml
Labels: cla: yes, size/S

#378 add rama chavali as networking wg lead
  WORKING-GROUPS.md
Labels: cla: yes, size/XS

#376 Update Feature Checklist to reflect RFC/Design Approval gates
  FEATURE-LIFECYCLE-CHECKLIST.md
Labels: cla: yes, size/XS

#380 Add justinwei2 as a member (remove juswei)
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#252 Add new Reviewer role with all the needed info
  ROLES.md
Labels: cla: yes, size/L

#386 Update steering as owner for community repo
  CODEOWNERS
Labels: cla: yes, size/XS

#383 add daixiang0 to istio members
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS
