Repository istio/community, pull requests merged in 2020-01, with the labels that each got.

#254 remove myself (vadimeisenbergibm) from Istio developers/maintainers
  org/istio.yaml
Labels: cla: yes, size/XS

#256 Setup org automation based on config file
  Makefile
  org/README.md
  org/config_test.go
  org/istio.yaml
Labels: cla: yes, size/XXL

#257 Add process to join the org via automation
  .github/ISSUE_TEMPLATE/organization-membership-request.md
  .github/pull_request_template.md
  ROLES.md
  org/README.md
Labels: cla: yes, size/M

#258 update affiliation
  TECH-OVERSIGHT-COMMITTEE.md
Labels: cla: yes, size/XS

#259 Add justinpettit to the org
  org/istio.yaml
Labels: cla: yes, size/XS

#263 add Rama Chavali as Pilot maintainer
  org/istio.yaml
Labels: cla: yes, size/XS

#264 Remove deleted github account from org
  org/istio.yaml
Labels: cla: yes, size/XS

#265 Remove @sushicw as member and config maintainer
  org/istio.yaml
Labels: cla: yes, size/XS

#266 Add ayj to networking
  org/istio.yaml
Labels: cla: yes, size/XS

#268 Add @jackkleeman to the org
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#267 Add release 1.5 managers
  org/istio.yaml
Labels: cla: yes, size/S

#270 Add costinm as an owner of networking
  org/istio.yaml
Labels: cla: yes, size/XS

#269 move jasonwzm to ux maintainers group
  org/istio.yaml
Labels: cla: yes, size/XS

#260 Add sniperking1234 to the org
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#261 Add zqzzq to the org
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS
