Repository istio/community, pull requests merged in 2020-08, with the labels that each got.

#387 Add Mitch Connors as UX WG Lead
  WORKING-GROUPS.md
Labels: cla: yes, size/XS

#390 Update istio.yaml - jgkogan joining Istio org
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#389 Add davidraskin as member
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#392 add chlins as member
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#398 Give steering committe write access to community repo
  org/istio.yaml
Labels: cla: yes, size/XS

#397 Remove 404 github user
  org/istio.yaml
Labels: cla: yes, size/XS

#395 Remove mention of admin rights from release managers and add release notes
  ROLES.md
Labels: cla: yes, size/XS

#322 Split organization yamls
  go.sum
  org/README.md
  org/admins.yaml
  org/config_test.go
  org/developers.yaml
  org/gen.go
  org/istio.yaml
  org/members.yaml
  org/repos.yaml
  org/teams.yaml
  prow/sync-org.sh
Labels: cla: yes, size/XXL

#361 Updating Steering Committee charter
  STEERING-COMMITTEE.md
Labels: cla: yes, size/L

#404 Describe new Steering Committee model & add election docs
  README.md
  steering/CHARTER.md
  steering/CONTRIBUTION-FORMULA.md
  steering/README.md
  steering/elections/2020/README.md
  steering/elections/2020/VOTERS.md
  steering/elections/2020/janedoe.md
  steering/elections/README.md
Labels: cla: yes, size/L

#405 Remove outdated join method
  .github/ISSUE_TEMPLATE/organization-membership-request.md
  .github/pull_request_template.md
Labels: cla: yes, size/S

#407 Add ceposta for nomination to steering
  steering/elections/2020/ceposta.md
Labels: cla: yes, size/S

#409 Nominate hzxuzhonghu to steering committe
  steering/elections/2020/hzxuzhonghu.md
Labels: cla: yes, size/S

#410 Add Salesforce representative
  steering/README.md
Labels: cla: yes, ok-to-test, size/XS

#411 Add davidhauck to teams.yaml
  org/developers.yaml
  org/teams.yaml
Labels: cla: yes, ok-to-test, size/XS
