Repository istio/community, pull requests merged in 2020-10, with the labels that each got.

#465 add our new steering members to the list in github
  org/teams.yaml
Labels: cla: yes, size/XS

#466 Add 1.8 release manager group
  org/teams.yaml
Labels: cla: yes, size/XS

#467 Add me as developer
  org/developers.yaml
  org/members.yaml
Labels: cla: yes, size/XS

#445 Add PSWG github team
  org/teams.yaml
Labels: cla: yes, size/S

#468 Replace Jacob Delgado with Neeraj Poddar for Product Security WG lead
  WORKING-GROUPS.md
Labels: cla: yes, size/XS

#469 Add Vincent Hou as a developer in istio community
  org/developers.yaml
Labels: cla: yes, ok-to-test, size/XS

#461 Test & Release Maintainers/Operations replaced by Operations Maintainers
  org/teams.yaml
Labels: cla: yes, size/S

#473 update org admins
  org/admins.yaml
Labels: cla: yes, size/XS

#471 username change for Cynthia Coan
  org/members.yaml
  org/teams.yaml
Labels: cla: yes, size/XS

#474 Add permissions in enhancements repo
  org/gen.go
Labels: cla: yes, size/XS

#478 Update steering committee member list
  steering/README.md
Labels: cla: yes, size/XS

#479 Add Monkeyanator to members
  org/developers.yaml
Labels: cla: yes, ok-to-test, size/XS

#480 Updated TOC list to reflect current members
  TECH-OVERSIGHT-COMMITTEE.md
Labels: cla: yes, size/XS

#481 Add self as developer and member
  org/developers.yaml
Labels: cla: yes, ok-to-test, size/XS

#482 Add shamsher31 to UX WG maintainers
  org/teams.yaml
Labels: cla: yes, size/XS

#484 Update sync-org.sh
  prow/sync-org.sh
Labels: cla: yes, size/XS

#485 Revert "Update sync-org.sh"
  prow/sync-org.sh
Labels: cla: yes, size/XS

#487 Update TECH-OVERSIGHT-COMMITTEE.md
  TECH-OVERSIGHT-COMMITTEE.md
Labels: cla: yes, size/XS

#488 Add link to YouTube playlist of meeting recordings.
  TECH-OVERSIGHT-COMMITTEE.md
Labels: cla: yes, size/XS

#489 org: add `yskopets` to developers
  org/developers.yaml
Labels: cla: yes, ok-to-test, size/XS

#490 Update TECH-OVERSIGHT-COMMITTEE.md
  TECH-OVERSIGHT-COMMITTEE.md
Labels: cla: yes, size/XS

#492 Update to steering committee members list
  org/teams.yaml
Labels: cla: yes, size/XS

#493 Add self as developer and member
  org/developers.yaml
Labels: cla: yes, ok-to-test, size/XS
