Repository istio/community, pull requests merged in 2020-02, with the labels that each got.

#271 Update STEERING-COMMITTEE.md
  STEERING-COMMITTEE.md
Labels: cla: yes, ok-to-test, size/S

#272 Application for membership for jacob-delgado
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#262 add JHDST to the org
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#275 Add sdake to the T&R maintainers.
  org/istio.yaml
Labels: cla: yes, size/XS

#274 update current working groups
  WORKING-GROUPS.md
Labels: cla: yes, size/S

#276 Add craigbox as Istio GitHub member
  org/istio.yaml
Labels: cla: yes, ok-to-test, size/XS

#279 Add Neeraj Poddar as Istio P&T WG maintainer
  org/istio.yaml
Labels: cla: yes, size/XS

#280 propose to add a few members to doc infra
  org/istio.yaml
Labels: cla: yes, size/XS

#281 Remove conflicting CoC
  VALUES.md
Labels: cla: yes, size/XS

#282 Add myself to istio/wg-networking-maintainers-data-plane team member
  org/istio.yaml
Labels: cla: yes, size/XS

#283 Add nrjpoddar to Networking WG maintainer list
  org/istio.yaml
Labels: cla: yes, size/XS

#284 Take a riff off Asimov's first law of robotics
  VALUES.md
Labels: cla: yes, size/XS
