Repository istio/community, pull requests merged in 2021-01, with the labels that each got.

#507 Remove doc WG lead
  WORKING-GROUPS.md
Labels: cla: yes, size/XS

#508 Remove developer who removed github account
  org/developers.yaml
Labels: cla: yes, size/XS

#509 apply for istio-membership - su225
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#510 Ram takes Dan's Steering seat
  steering/README.md
Labels: cla: yes, size/XS

#511 update steering member
  org/teams.yaml
Labels: cla: yes, size/XS

#512 Update members.yaml
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#495 Change Development phase to Experimental phase of a feature to better represent the state of a feature
  FEATURE-LIFECYCLE.md
Labels: cla: yes, size/M

#514 Update members.yaml
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#515 Update members.yaml
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#460 Explicitly add Code of Conduct, derived from Contributor Covenant v2.0
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
Labels: cla: yes, size/L
