Repository istio/community, pull requests merged in 2021-06, with the labels that each got.

#576 Restore triage test group
  org/teams.yaml
Labels: cla: yes, size/S

#578 Update PSWG maintainers
  org/teams.yaml
Labels: cla: yes, size/XS

#580 Add BinacsLee as a member
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#583 Update WORKING-GROUPS.md to accurately reflect workgroup leads
  WORKING-GROUPS.md
Labels: cla: yes, size/S

#585 add silenceshell as developer
  org/developers.yaml
Labels: cla: yes, needs-ok-to-test, ok-to-test, size/XS

#587 add self as developer
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#586 Use triage for user permissions
  org/developers.yaml
  org/gen.go
  org/members.yaml
  org/teams.yaml
Labels: cla: yes, size/L

#590 Add ryantking as a member
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#593 Update org default perms to triage
  org/gen.go
Labels: cla: yes, size/XS

#594 Revert "Update org default perms to triage"
  org/gen.go
Labels: cla: yes, size/XS

#589 Update toc
  TECH-OVERSIGHT-COMMITTEE.md
  org/admins.yaml
  org/teams.yaml
Labels: cla: yes, size/XS

#592 Get rid of members
  org/README.md
  org/config_test.go
  org/developers.yaml
  org/gen.go
  org/members.yaml
Labels: cla: yes, size/L

#597 Add new Steering members as Istio org members
  org/members.yaml
Labels: cla: yes, size/XS

#596 Start 2021 Community Seat election process.
  org/teams.yaml
  steering/CONTRIBUTION-FORMULA.md
  steering/README.md
  steering/elections/2021/README.md
  steering/elections/2021/VOTERS.md
Labels: cla: yes, size/L

#598 Updates to TOC
  TECH-OVERSIGHT-COMMITTEE.md
  org/teams.yaml
Labels: cla: yes, size/M

#599 Remove truongnh1992 from members
  org/members.yaml
Labels: cla: yes, size/XS

#601 add Haleygo as member
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#600 Updates to support using Elekto
  steering/elections/2020/README.md
  steering/elections/2020/sample-janedoe.md
  steering/elections/2021/README.md
  steering/elections/2021/nomination-template.md
  steering/elections/README.md
Labels: cla: yes, size/M

#602 Configure Peribolos to configure repos
  prow/sync-org.sh
Labels: cla: yes, size/XS

#603 Add myself to admins
  org/admins.yaml
Labels: cla: yes, size/XS

#605 Add steering write to community
  org/teams.yaml
Labels: cla: yes, size/XS

#606 Update teams
  org/teams.yaml
Labels: cla: yes, size/XS
