Repository istio/community, pull requests merged in 2021-11, with the labels that each got.

#664 Update requirements for early disclosure list
  EARLY-DISCLOSURE.md
Labels: size/S, cla: yes

#665 add kfaseela to istio org
  org/members.yaml
Labels: cla: yes

#663 Use sigs.k8s.io/yaml library
  go.mod
  go.sum
  org/gen.go
Labels: size/M, cla: yes
