Repository istio/community, pull requests merged in 2021-09, with the labels that each got.

#641 Update nrjpoddar's company affliation
  TECH-OVERSIGHT-COMMITTEE.md
Labels: size/XS, cla: yes

#642 add member
  org/members.yaml
Labels: size/XS, cla: yes, ok-to-test

#644 Fix duplicate word word in charter
  steering/CHARTER.md
Labels: size/XS, cla: yes

#643 add member bryankaraffa
  org/members.yaml
Labels: size/XS, cla: yes, ok-to-test

#645 add rvennam to docs infra
  org/teams.yaml
Labels: size/XS, cla: yes

#646 Grant Craig and Eric admin permission to ZH pages
  org/teams.yaml
Labels: size/XS, cla: yes

#647 Replaced Doug Davis (IBM) with Srihari Angaluri (IBM).
  steering/README.md
Labels: size/XS, cla: yes, ok-to-test

#649 Adding knabben as member
  org/members.yaml
Labels: size/XS, cla: yes, ok-to-test

#650 Update T&R WG Lead, alphabetize list by last name
  WORKING-GROUPS.md
  org/teams.yaml
Labels: size/S, cla: yes

#651 replace Neeraj with Iris in Steering
  steering/README.md
Labels: size/XS, cla: yes

#652 update team.yaml
  org/teams.yaml
Labels: size/XS, cla: yes

#654 Add kfreez as member
  org/members.yaml
Labels: size/XS, cla: yes, ok-to-test

#653 Add the release manager for istio 1.12
  org/teams.yaml
Labels: size/XS, cla: yes
