Repository istio/community, pull requests merged in 2021-07, with the labels that each got.

#564 Create BRANDING.md
  BRANDING.md
Labels: cla: yes, needs-ok-to-test, size/M

#595 Adding self to security WG team
  org/teams.yaml
Labels: cla: yes, size/XS

#610 Add ChenglongGao327 as a member
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#611 add the release manager for Istio 1.11
  org/teams.yaml
Labels: cla: yes, size/XS

#612 Add nicole-lihui as a member
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#613 add l8huang to member list
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#614 Add myself to 1.11 release managers team
  org/teams.yaml
Labels: cla: yes, size/XS

#616 Nomination details for nrjpoddar's Steering 2021
  steering/elections/2021/candidate-nrjpoddar.md
Labels: cla: yes, size/S

#617 Nominate hzxuzhonghu for steering 2021
  steering/elections/2021/candidate-hzxuzhonghu.md
Labels: cla: yes, size/S

#615 Self nomination for Istio Steering community seat
  steering/elections/2021/linsun.md
Labels: cla: yes, size/S

#618 Zack Butcher nomination for 2021 Steering
  steering/elections/2021/candidate-zackbutcher.md
Labels: cla: yes, size/XS

#619 Rename linsun.md to candidate-linsun.md
  steering/elections/2021/candidate-linsun.md
Labels: cla: yes, size/XS

#621 add gy95 as Istio org member
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS

#622 Update TL list
  org/teams.yaml
Labels: cla: yes, size/XS

#623 Get rid of perf and scalability group
  org/teams.yaml
Labels: cla: yes, size/XS

#625 Add release managers page and remove 1.1 and 1.2 release managers
  RELEASE_MANAGERS.md
  org/teams.yaml
Labels: cla: yes, size/L

#626 Add mathetake to members.yaml.
  org/members.yaml
Labels: cla: yes, ok-to-test, size/XS
