Repository istio/community, pull requests merged in 2021-05, with the labels that each got.

#561 Empower myself a little more in the docs group
  org/teams.yaml
Labels: cla: yes, size/XS

#562 add stevenctl to environments
  org/teams.yaml
Labels: cla: yes, size/XS

#566 Add test triagers
  go.mod
  go.sum
  org/developers.yaml
  org/members.yaml
  org/teams.yaml
Labels: cla: yes, size/XXL

#568 Temoprarily revert triage
  org/teams.yaml
Labels: cla: yes, size/S

#569 apply for member: sergii-ssh
  org/members.yaml
Labels: cla: yes, needs-ok-to-test, ok-to-test, size/XS

#570 Update TOC membership and admin roles
  ADMINS-FOR-ISTIO.md
  TECH-OVERSIGHT-COMMITTEE.md
  org/admins.yaml
  org/teams.yaml
Labels: cla: yes, size/S

#572 Add Monkeyanator to Environments maintainers
  org/teams.yaml
Labels: cla: yes, size/XS

#577 make stevenctl networking wg lead
  WORKING-GROUPS.md
  org/teams.yaml
Labels: cla: yes, size/XS
