Repository istio/community, pull requests merged in 2022-04, with the labels that each got.

#712 mark Sven as having left TOC
  TECH-OVERSIGHT-COMMITTEE.md
Labels: size/XS

#716 adding myself to the members list
  org/members.yaml
Labels: size/XS, ok-to-test

#717 Add Chen-Xintong to the member list
  org/members.yaml
Labels: size/XS, ok-to-test

#721 Add my-git9 to istio member list
  org/members.yaml
Labels: size/XS, ok-to-test

#719 Add get-istioctl to repos.yaml
  org/repos.yaml
  org/teams.yaml
Labels: size/XS

#723 Update member qwertyuiop888 to albertsun0
  org/members.yaml
Labels: size/XS

#724 add release managers for 1.14
  org/teams.yaml
Labels: size/XS

#715 Update CONTRIBUTION-FORMULA.md
  steering/CONTRIBUTION-FORMULA.md
Labels: size/S

#726 Add myself to members list
  org/members.yaml
Labels: size/XS, ok-to-test

#727 add me to members yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#728 add me to members
  org/members.yaml
Labels: size/XS, ok-to-test
