Repository istio/community, pull requests merged in 2022-08, with the labels that each got.

#781 Update security group leads and product security leads
  WORKING-GROUPS.md
Labels: size/XS

#785 Add Tong Li as a member of Chinese Doc Maintainers
  org/teams.yaml
Labels: size/XS

#766 Update product security repo permissions
  org/teams.yaml
Labels: size/S

#786 add hzxuzhonghu to security maintainers group
  org/teams.yaml
Labels: size/XS

#787 add-jjtischer to members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#788 add rrobb-aspen to members list
  org/members.yaml
Labels: size/XS, ok-to-test
