Repository istio/community, pull requests merged in 2022-07, with the labels that each got.

#757 add saltbo to members
  org/members.yaml
Labels: size/XS, ok-to-test

#760 add michelle951 as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#759 add shirleyyLi as member
  org/members.yaml
Labels: size/XS, ok-to-test

#761 Update PSWG and current set of release manaagers
  org/teams.yaml
Labels: size/S

#762 add aryan16 in security maintainers group
  org/teams.yaml
Labels: size/XS

#763 Add ydFu to the member list.
  org/members.yaml
Labels: size/XS, ok-to-test

#764 add xichengliudui to members
  org/members.yaml
Labels: size/XS, ok-to-test

#767 add fatedier to members
  org/members.yaml
Labels: size/XS, ok-to-test

#769 Remove Sven in org. Already emeritus in TOC.
  org/admins.yaml
  org/teams.yaml
Labels: size/XS

#768 Update release managers
  RELEASE_MANAGERS.md
Labels: size/M

#773 Add Francis Zhou for membership
  org/members.yaml
Labels: size/XS, ok-to-test

#772 Add Product Security Members
  org/members.yaml
Labels: size/XS

#774 add yxxhero as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#775 add wuwuwuyanz as member
  org/members.yaml
Labels: size/XS, ok-to-test

#776 add NiuYinlong1994 as member
  org/members.yaml
Labels: size/XS, ok-to-test

#777 add xiaomudk to members
  org/members.yaml
Labels: size/XS, ok-to-test

#778 Adding Istio 1.15 release managers
  org/teams.yaml
Labels: size/S

#779 Add ZiyangXiao for membership
  org/members.yaml
Labels: size/XS, ok-to-test

#780 Add ZiyangXiao to 1.15 release managers
  org/teams.yaml
Labels: size/XS
