Repository istio/community, pull requests merged in 2022-10, with the labels that each got.

#816 Zack Butcher 2022 Steering Election
  steering/elections/2022/candidate-zackbutcher.md
Labels: size/S

#813 Create candidate-craigbox.md
  steering/elections/2022/candidate-craigbox.md
Labels: size/M

#812 Add kfaseela as nominee for steering 2022
  steering/elections/2022/candidate-kfaseela.md
Labels: size/S

#808 Add candidate hzxuzhonghu
  steering/elections/2022/candidate-hzxuzhonghu.md
Labels: size/M

#819 Add current Steering Committee members to VOTERS
  steering/elections/2022/VOTERS.md
Labels: size/XS

#820 remove timezone in calendar
  WORKING-GROUPS.md
Labels: size/XS

#818 Add Solo.io Ambient Mesh contributors to steering 2022 VOTERS list
  steering/elections/2022/VOTERS.md
Labels: size/S

#822 Submit election files
  steering/elections/2022/election.yaml
  steering/elections/2022/election_desc.md
  steering/elections/2022/voters.yaml
Labels: size/L

#823 Fix common makefile to copy files
  common/Makefile.common.mk
Labels: size/XS

#825 Corrections to candidate profile pages for Elekto.
  steering/elections/2022/candidate-ceposta.md
  steering/elections/2022/candidate-craigbox.md
  steering/elections/2022/candidate-hzxuzhonghu.md
  steering/elections/2022/candidate-irisdingbj.md
  steering/elections/2022/candidate-kfaseela.md
  steering/elections/2022/election.yaml
Labels: size/S

#826 Add "Election Officers" team
  org/members.yaml
  org/teams.yaml
Labels: size/S

#828 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#829 Create CODEOWNERS
  steering/elections/CODEOWNERS
Labels: size/XS

#831 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#835 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#836 Update teams.yaml
  org/teams.yaml
Labels: size/XS

#837 Add FangtingYan to members list
  org/members.yaml
Labels: size/XS, ok-to-test

#834 adding abasitt to the member list
  org/members.yaml
Labels: size/XS, ok-to-test

#839 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#840 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#832 Add Mitch Connors to the TOC
  TECH-OVERSIGHT-COMMITTEE.md
Labels: size/S

#842 Add Fish-pro to istio member list
  org/members.yaml
Labels: size/XS, ok-to-test

#843 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#845 Added myself to members.
  org/members.yaml
Labels: size/XS, ok-to-test

#846 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#847 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: size/XS, auto-merge, release-notes-none

#848 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#849 Add Oksana Baranova to members of Istio community
  org/members.yaml
Labels: size/XS, ok-to-test

#851 apply for member
  org/members.yaml
Labels: size/XS, ok-to-test

#852 Update Fasella and Frank Docs maintainership to help PR approvals
  org/teams.yaml
Labels: size/XS
