Repository istio/community, pull requests merged in 2022-12, with the labels that each got.

#904 Remove former maintainers
  org/teams.yaml
Labels: size/M

#906 add giantcroc as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#908 Thank our emeritus maintainers
  org/emeritus.yaml
Labels: size/M

#907 Add me to admins
  org/admins.yaml
  org/teams.yaml
Labels: size/XS

#830 Update some things I've handed over upon leaving Google.
  ADMINS-FOR-ISTIO.md
Labels: size/S

#909 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#910 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#883 Update lead of "Extensions and Telemetry"
  WORKING-GROUPS.md
Labels: size/XS

#911 Update co-lead of Extensions and Telemetry
  WORKING-GROUPS.md
Labels: size/XS

#912 Update 1.16 RM from Tong Li to Mariam John
  RELEASE_MANAGERS.md
  org/teams.yaml
Labels: size/XS

#913 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#916 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#917 Automator: update common-files@master in istio/community@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#899 add liangyongzhenya as member
  org/members.yaml
Labels: size/XS, ok-to-test

#918 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#920 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#921 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#923 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#924 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
