Repository istio/community, pull requests merged in 2022-02, with the labels that each got.

#689 Add Andrea Ma as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#686 Update members of the PSWG
  org/teams.yaml
Labels: size/XS

#691 Add Andrea Ma to PSWG
  org/teams.yaml
Labels: size/XS

#690 Update members.yaml
  org/members.yaml
  org/teams.yaml
Labels: size/XS, ok-to-test

#685 Add hanxiaop as a UX maintainer
  org/teams.yaml
Labels: size/XS

#687 Removing self from Operations Maintainers
  org/teams.yaml
Labels: size/XS

#692 add kerthcet as member
  org/members.yaml
Labels: size/XS, ok-to-test

#694 Remove members not meeting feb 14 requirements
  EARLY-DISCLOSURE.md
Labels: size/XS

#681 Remove mjog as WG lead from E&T
  WORKING-GROUPS.md
Labels: size/XS

#695 add zirain as E&T maintainer
  org/teams.yaml
Labels: size/XS

#697 Update steering membership
  org/members.yaml
  org/teams.yaml
Labels: size/S

#698 Update Steering membership for 2022-2023.
  steering/README.md
Labels: size/XS

#701 add shivanshu1333 as member
  org/members.yaml
Labels: size/XS, ok-to-test

#703 add feeltimeQ as member
  org/members.yaml
Labels: size/XS, ok-to-test

#705 Add deveshkandpal1224
  org/members.yaml
Labels: size/XS, ok-to-test
