Repository istio/community, pull requests merged in 2022-11, with the labels that each got.

#853 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#855 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#856 Add sschepens as member
  org/members.yaml
Labels: size/XS, ok-to-test

#858 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#859 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#860 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#862 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#865 Update Mitch's affiliation
  TECH-OVERSIGHT-COMMITTEE.md
Labels: size/XS

#863 Update steering members after the elections 2022
  steering/README.md
Labels: size/XS

#864 Update steering members
  org/teams.yaml
Labels: size/XS

#866 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#861 add zirain as ENV Maintainers
  org/teams.yaml
Labels: size/XS

#868 adding astronaut0131 to the member list
  org/members.yaml
Labels: size/XS, ok-to-test

#869 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#870 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#867 Add inner team members to outer list - Prevent rmv/add during sync
  org/config_test.go
  org/teams.yaml
Labels: size/M

#872 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#873 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#874 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#875 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#878 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#880 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#882 Doug has moved on
  WORKING-GROUPS.md
Labels: size/XS

#884 add EItnaya to members
  org/members.yaml
Labels: size/XS, ok-to-test

#886 Fix role access for ztunnel
  org/gen.go
  org/repos.yaml
Labels: size/XS

#887 add aimuz to members
  org/members.yaml
Labels: size/XS, ok-to-test

#888 Nominating myself back as a maintainer
  org/teams.yaml
Labels: size/XS

#877 Update teams.yaml
  org/teams.yaml
Labels: size/XS

#891 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#890 Add keithmattix to members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#892 Test consistency between Leads, Maintainers, and WG
  org/config_test.go
  org/teams.yaml
Labels: size/M

#894 Add chaunceyjiang to members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#893 correct company
  WORKING-GROUPS.md
Labels: size/XS

#896 Add self as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#897 Add self as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#900 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#901 Adding hemendrateli as member
  org/members.yaml
Labels: size/XS, ok-to-test

#903 add 12345XXX to members
  org/members.yaml
Labels: size/XS, ok-to-test
