Repository istio/community, pull requests merged in 2022-09, with the labels that each got.

#790 Update members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#791 Add new zh docs maintainers
  org/teams.yaml
Labels: size/XS

#792 Minor doc updates
  CONTRIBUTING.md
  RELEASE_MANAGERS.md
  WORKING-GROUP-PROCESSES.md
Labels: size/M

#793 Update teams.yaml
  org/teams.yaml
Labels: size/XS

#794 add jzhupup as member
  org/members.yaml
Labels: size/XS, ok-to-test

#795 Start 2022 election process.
  steering/README.md
  steering/elections/2022/README.md
  steering/elections/2022/VOTERS.md
  steering/elections/2022/nomination-template.md
  steering/elections/README.md
Labels: size/L

#797 Add PlatformLC as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#798 Google nominates Cameron Etezadi to its open seat
  steering/README.md
Labels: size/XS

#800 fix wrong format
  steering/README.md
Labels: size/XS

#802 add irisdingbj to security WG maintainer list
  org/teams.yaml
Labels: size/XS

#803 Add imroc as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#806 Apply for becoming a member. Thank you
  org/members.yaml
Labels: size/XS, ok-to-test

#807 Add kfaseela to Docs Maintainers
  org/teams.yaml
Labels: size/XS

#810 added Christian Posta as nominee for steering 2022
  steering/elections/2022/candidate-ceposta.md
Labels: size/S
