Repository istio/community, pull requests merged in 2023-05, with the labels that each got.

#1036 update Steven Landow's association
  WORKING-GROUPS.md
Labels: size/XS

#1041 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1043 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1044 added phillipgibson to members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#1046 added jiecloud to members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#1047 Introduce `ztunnel` team
  org/teams.yaml
Labels: size/XS

#1049 Add ty-dc to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1051 Add myshkin5 to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1050 Add Jacob Delgado as Istio Env maintainer
  org/teams.yaml
Labels: size/XS

#1053 Clarify TOC election eligibility
  TECH-OVERSIGHT-COMMITTEE.md
Labels: size/S

#1056 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1057 Update README.md
  steering/README.md
Labels: size/XS

#1058 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1052 Update charter to reflect trademark ownership
  steering/CHARTER.md
Labels: size/XS

#1048 Simplfy org configuration
  org/gen.go
  org/teams.yaml
Labels: size/L

#1059 Add yankay to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1060 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1061 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1062 Add kdorosh to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1063 Update group to send email about joining Istio PSWG
  EARLY-DISCLOSURE.md
Labels: size/XS

#1064 Add keithmattix/Microsoft to PSWG
  EARLY-DISCLOSURE.md
  org/teams.yaml
Labels: size/XS

#1065 Add additional test to ensure "Maintainers" actually maintain something
  org/config_test.go
Labels: size/XS, release-notes-none

#1067 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1068 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/S, auto-merge, release-notes-none

#1070 add member rokkiter
  org/members.yaml
Labels: size/XS, ok-to-test

#1071 add member MorrisLaw
  org/members.yaml
Labels: size/XS, ok-to-test
