Repository istio/community, pull requests merged in 2023-09, with the labels that each got.

#1198 Apply for istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1200 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1201 Add cinderyx as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#1202 add wwwnay as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#1203 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1205 Add LinSun to steering
  steering/README.md
Labels: size/XS

#1204 Add 1.20 release managers
  org/teams.yaml
Labels: size/XS

#1206 add member scydas
  org/members.yaml
Labels: size/XS, ok-to-test

#1208 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1207 Add my-git9 to Chinese doc maintainer
  org/teams.yaml
Labels: size/XS

#1209 Update Working Groups Lists
  WORKING-GROUPS.md
Labels: size/XS

#1210 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1211 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/S, auto-merge, release-notes-none
