Repository istio/community, pull requests merged in 2023-10, with the labels that each got.

#1212 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/S, auto-merge, release-notes-none

#1213 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1214 Remove obaranov1 as no longer a GH user
  org/members.yaml
Labels: size/XS

#1215 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1216 Update WG Calendar
  WORKING-GROUPS.md
Labels: size/S

#1217 Update WG weekly meeting section
  WORKING-GROUPS.md
Labels: size/XS

#1218 Fix another broken link
  WORKING-GROUPS.md
Labels: size/XS

#1219 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1220 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1223 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1222 Add HeavenTonight as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#1224 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1221 Apply for membership
  org/members.yaml
Labels: size/XS, ok-to-test

#1225 Apply for membership: tanujd11
  org/members.yaml
Labels: size/XS, ok-to-test

#1226 apply member
  org/members.yaml
Labels: size/XS, ok-to-test

#1227 add ii2day to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1228 Add usernameisnull as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#1229 update release_managers.md
  RELEASE_MANAGERS.md
Labels: size/M

#1230 add husnialhamdani as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#1231 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1234 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1233 Add zirain to 1.20 release team
  org/teams.yaml
Labels: size/XS

#1236 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1237 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1238 Update lizan's affilication
  WORKING-GROUPS.md
Labels: size/XS

#1239 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1242 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1232 Add jaellio to PSWG
  org/teams.yaml
Labels: size/XS

#1241 Update README.md
  README.md
Labels: size/S, ok-to-test

#1243 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1244 Add unicell to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1245 Apply member
  org/members.yaml
Labels: size/XS, ok-to-test

#1246 Update member name
  org/members.yaml
Labels: size/XS, ok-to-test

#1247 Automator: update common-files@master in istio/community@master
  LICENSE
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
