Repository istio/community, pull requests merged in 2023-06, with the labels that each got.

#1072 Add pmerrison to PSWG
  org/teams.yaml
Labels: size/XS

#1074 apply for a istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1075 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1076 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1077 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1079 Apply for a Istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1078 Add yanggangtony to istio member list
  org/members.yaml
Labels: size/XS, ok-to-test

#1081 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1082 Apply for a Istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1083 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1085 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1086 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1087 Remove jtischer-acasi - no longer appears in github
  org/members.yaml
Labels: size/XS

#1089 add krisztianfekete to members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#1088 add member yitingdc
  org/members.yaml
Labels: size/XS, ok-to-test

#1091 samzong applies to join Istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1090 Add kfaseela as Test and Release maintainer
  org/teams.yaml
Labels: size/XS

#1093 apply for istio membership
  org/members.yaml
Labels: size/XS, ok-to-test

#1094 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1095 huan555 applies to join Istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1096 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#1097 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1098 add cebernardi as member
  org/members.yaml
Labels: size/XS, ok-to-test

#1099 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1100 add-jjtischer
  org/members.yaml
Labels: size/XS, ok-to-test

#1101 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1103 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1104 Update teams.yaml
  org/teams.yaml
Labels: size/XS

#1102 Add Stevenjin8 as member
  org/members.yaml
Labels: size/XS, ok-to-test

#1106 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
