Repository istio/community, pull requests merged in 2023-02, with the labels that each got.

#961 Add jiuker as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#960 Google update sc
  org/teams.yaml
  steering/README.md
Labels: size/XS

#962 add hypernovasunnix to members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#964 Add ksubrmnn as member
  org/members.yaml
Labels: size/XS, ok-to-test

#966 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#965 requesting org membership for Ian Rudie, user: ilrudie
  org/members.yaml
Labels: size/XS, ok-to-test

#967 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#968 add wulianglongrd as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#969 Add new steering members
  steering/README.md
Labels: size/S

#970 Update steering members
  org/members.yaml
  org/teams.yaml
Labels: size/XS

#971 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#972 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#973 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#975 Update teams.yaml
  org/teams.yaml
Labels: size/XS

#977 Add Zhuzhenghao as member
  org/members.yaml
Labels: size/XS, ok-to-test

#978 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#980 Add nameYULI as member
  org/members.yaml
Labels: size/XS, ok-to-test

#982 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#983 Add johndlong as member
  org/members.yaml
Labels: size/XS, ok-to-test

#984 Add Pawan-Bishnoi as member
  org/members.yaml
Labels: size/XS, ok-to-test

#985 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#986 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#987 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#988 Add SRodi to org member list
  org/members.yaml
Labels: size/XS, ok-to-test

#989 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#990 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#991 Fix sync issue - Remove inactive sbezverk
  org/members.yaml
Labels: size/XS

#992 Add thelinuxfoundation as members
  org/members.yaml
Labels: size/XS

#996 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#997 Add Songjoy as member
  org/members.yaml
Labels: size/XS, ok-to-test

#998 Update teams.yaml
  org/teams.yaml
Labels: size/XS
