Repository istio/community, pull requests merged in 2023-07, with the labels that each got.

#1108 Add yeedove to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1109 update Huawei SC seat
  org/teams.yaml
  steering/README.md
Labels: size/XS

#1110 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1111 Apply for a Istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1112 Apply for a Istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1113 Apply for a Istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1116 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1119 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1120 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1118 Add dhawton as English docs maintainer
  org/teams.yaml
Labels: size/XS

#1121 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1122 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1125 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1117 Move to new org tool
  go.mod
  go.sum
  org/config_test.go
  org/gen.go
  prow/sync-org.sh
Labels: size/XXL

#1126 Paperwork for 2023 election.
  steering/elections/2023/README.md
  steering/elections/2023/election.yaml
  steering/elections/2023/election_desc.md
  steering/elections/2023/nomination-template.md
Labels: size/L

#1127 update zirain's association
  WORKING-GROUPS.md
Labels: size/XS

#1128 Add initial voters list
  steering/elections/2023/voters.yaml
Labels: size/L

#1129 Nomination for Steering for 2023
  steering/elections/2023/candidate-craigbox.md
Labels: size/S

#1131 Applying Arka to become Istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1132 adding arkodg as an org member
  org/members.yaml
Labels: size/XS, ok-to-test

#1130 Adds Daneyon Hansen as Org Member
  org/members.yaml
Labels: size/XS, ok-to-test

#1133 Add Ignasi Barrera to the org members
  org/members.yaml
Labels: size/XS, ok-to-test

#1134 Steering Committee Nomination for Keith Mattix
  steering/elections/2023/candidate-keithmattix.md
Labels: size/S

#1135 add TOC members to voters.yaml
  steering/elections/2023/voters.yaml
Labels: size/XS

#1137 Add zhxie as an org member
  org/members.yaml
Labels: size/XS, ok-to-test

#1138 Steering Election Nomination - 2023
  steering/elections/2023/candidate-kfaseela.md
Labels: size/S

#1139 add steering nomination for 2023
  steering/elections/2023/candidate-irisdingbj.md
Labels: size/S

#1140 Add José Carlos Chávez to the org members
  org/members.yaml
Labels: size/XS, ok-to-test

#1142 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1143 Add zhiyingfang2022 as an org member
  org/members.yaml
Labels: size/XS, ok-to-test

#1145 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1146 Update Steering README for 2023
  steering/README.md
Labels: size/XS

#1147 Add 2023 spreadsheet
  steering/README.md
Labels: size/XS

#1148 Steering Committee Nomination for Kebe Liu
  steering/elections/2023/candidate-kebe7jun.md
Labels: size/S

#1149 Add mike-weiner as Member
  org/members.yaml
Labels: size/XS, ok-to-test

#1150 Fix sync-community - Remove geeknoid
  org/members.yaml
Labels: size/XS

#1151 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/tracing.sh
Labels: size/L, auto-merge, release-notes-none

#1152 Lemontrees123 want to join the Istio org
  org/members.yaml
Labels: size/XS, ok-to-test

#1153 Add richincapie to community
  org/members.yaml
Labels: size/XS, ok-to-test

#1155 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/tracing.sh
Labels: size/S, auto-merge, release-notes-none

#1157 Add Lin info to steering candidate
  steering/elections/2023/candidate-linsun.md
Labels: size/S

#1158 Create candidate-mitchconnors.md for 2023 steering election
  steering/elections/2023/candidate-mitchconnors.md
Labels: size/S

#1159 Add ZackButcher as Steering candidate
  steering/elections/2023/candidate-zackbutcher.md
Labels: size/S

#1160 Fix Elekto link
  steering/elections/2023/README.md
Labels: size/XS

#1161 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
