Repository istio/community, pull requests merged in 2023-08, with the labels that each got.

#1162 Add 0LuckyLove0 to the org Member
  org/members.yaml
Labels: size/XS, ok-to-test

#1163 Elections: elekto bug requires case sensitive github id for voters.yaml
  steering/elections/2023/voters.yaml
Labels: size/M

#1164 Update voters.yaml
  steering/elections/2023/voters.yaml
Labels: size/S

#1166 update the ID with case sensitivity
  org/members.yaml
Labels: size/XS

#1165 Election: Fix candidate profile links
  steering/elections/2023/candidate-ZackButcher.md
  steering/elections/2023/candidate-therealmitchconnors.md
Labels: size/XS

#1168 fix my ID with case sensitivity
  steering/elections/2023/voters.yaml
Labels: size/XS

#1169 Remove myself from working group leads.
  WORKING-GROUPS.md
Labels: size/XS

#1170 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1172 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1171 Adjust timezone link for more consistent results
  README.md
Labels: size/XS, ok-to-test

#1173 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1175 add Abirdcfly to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1177 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1178 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#1179 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1180 Add w12379564 to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1181 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1182 Replace Jacob Delgado with Josh Tischer as part of the PSWG
  org/teams.yaml
Labels: size/XS

#1183 add weizhoublue to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1185 add Accelerator96 to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1189 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1190 Add adams-shaun as community member
  org/members.yaml
Labels: size/XS, ok-to-test

#1191 Add liu-xg to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1192 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1193 Add pegasas to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1194 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1195 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1196 Apply for a Istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1197 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
