Repository istio/community, pull requests merged in 2023-03, with the labels that each got.

#1000 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#995 Add new CLA info as we transition to LF CLA
  CLA.md
  CONTRIBUTING.md
Labels: size/M

#1002 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1003 Add zengyuxing007 as member
  org/members.yaml
Labels: size/XS, ok-to-test

#1004 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1005 emeritus chaodaig
  org/emeritus.yaml
  org/members.yaml
  org/teams.yaml
Labels: size/XS

#1006 name added
  org/members.yaml
Labels: size/XS, ok-to-test

#1008 justedennnn : apply to be istio member
  org/members.yaml
Labels: size/XS, ok-to-test

#1007 add wlp1153468871 as member
  org/members.yaml
Labels: size/XS, ok-to-test

#1010 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1011 add helen-frank as member
  org/members.yaml
Labels: size/XS, ok-to-test

#1012 add tanberBro as member
  org/members.yaml
Labels: size/XS, ok-to-test

#1013 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/M, auto-merge, release-notes-none

#1014 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1016 Add gssjl2008 to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1017 Add asa3311 to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1018 Fix sync-community - Remove Francois (fpesce) as a member
  org/members.yaml
Labels: size/XS

#1019 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
Labels: size/L, auto-merge, release-notes-none

#1020 Add GregHanson to UX maintainers
  org/teams.yaml
Labels: size/XS

#1021 operations: add John and Stewart
  org/teams.yaml
Labels: size/XS
