Repository istio/community, pull requests merged in 2023-12, with the labels that each got.

#1268 Add myself to steering approval list
  org/teams.yaml
Labels: size/XS

#1267 Add yuval-k to org members
  org/members.yaml
Labels: size/XS, ok-to-test

#1269 Add leosarra to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1270 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1271 Add ShabanaD to members list
  org/members.yaml
Labels: size/XS, ok-to-test

#1273 add dhawton to PSWG
  org/teams.yaml
Labels: size/XS

#1274 Update members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#1276 Add sword-jin to members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#1275 Add srinivas to members list
  org/members.yaml
Labels: size/XS, ok-to-test

#1277 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1278 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1279 add name in member
  org/members.yaml
Labels: size/XS, ok-to-test

#1280 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1281 Add srampal to community members
  org/members.yaml
Labels: size/XS, ok-to-test

#1283 Add bochengchu to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1282 Update README.md about community meetings
  README.md
Labels: size/S

#1284 Add zengchongliner to community members
  org/members.yaml
Labels: size/XS, ok-to-test

#1285 Fix community meeting formatting
  README.md
Labels: size/XS

#1286 add member: tukwila to community members
  org/members.yaml
Labels: size/XS, ok-to-test
