Repository istio/community, pull requests merged in 2023-01, with the labels that each got.

#925 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#926 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#928 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#932 add fengshunli as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#933 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#934 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#935 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/XS, auto-merge, release-notes-none

#936 Update teams.yaml
  org/teams.yaml
Labels: size/XS

#937 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#938 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#939 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#941 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#929 Add pmerrison as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#942 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#927 Update teams.yaml
  org/teams.yaml
Labels: size/XS

#943 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#944 Update CODE-OF-CONDUCT.md
  CODE-OF-CONDUCT.md
Labels: size/L

#945 Update CODE-OF-CONDUCT.md to point to CNCF (correctly)
  CODE-OF-CONDUCT.md
Labels: size/XS

#946 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#947 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#948 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#949 members: add shashankram
  org/members.yaml
Labels: size/XS, ok-to-test

#950 Add bleggett as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#951 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#952 add peterj as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#953 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#954 Add Chirs A, required by CNCF
  org/members.yaml
Labels: size/XS

#955 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#957 Add whitneygriffith to members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#956 Add jaellio to members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#959 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
