Repository istio/community, pull requests merged in 2023-11, with the labels that each got.

#1248 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1249 Add Icarus9913 as an org member
  org/members.yaml
Labels: size/XS, ok-to-test

#1250 add tonya11en to org members
  org/members.yaml
Labels: size/XS, ok-to-test

#1251 Requesting to add arijitvt as member.
  org/members.yaml
Labels: size/XS, ok-to-test

#1252 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1254 Update CONTRIBUTION-FORMULA.md
  steering/CONTRIBUTION-FORMULA.md
Labels: size/S

#1255 Remove missing member, mrshengzyzy
  org/members.yaml
Labels: size/XS

#1258 Remove missing member, rrobb-aspen
  org/members.yaml
Labels: size/XS

#1259 Remove Google-Admin
  org/admins.yaml
  org/config_test.go
Labels: size/XS

#1260 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1261 Add Robb back with new GH username
  org/members.yaml
Labels: size/XS

#1264 Add syw14 to org member
  org/members.yaml
Labels: size/XS, ok-to-test

#1265 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1266 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none
