Repository istio/community, pull requests merged in 2024-03, with the labels that each got.

#1351 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1352 Add bincherry to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1355 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1356 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1358 Joining Istio Organization: Membership Request
  org/members.yaml
Labels: size/XS, ok-to-test

#1350 Remove requirement that TOC candidates be a Working Group Lead.
  TECH-OVERSIGHT-COMMITTEE.md
Labels: size/XS

#1359 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1360 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1362 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#1363 add dhawton to docs-infra team as well
  org/teams.yaml
Labels: size/XS

#1364 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1366 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1365 Add `thelinuxfoundation` as an admin
  go.mod
  go.sum
  org/admins.yaml
Labels: size/M, release-notes-none
