Repository istio/community, pull requests merged in 2024-04, with the labels that each got.

#1367 Replace VMware with Broadcom in EARLY-DISCLOSURE.md
  EARLY-DISCLOSURE.md
Labels: size/XS

#1369 Finish updating Google Steering members.
  org/members.yaml
  org/teams.yaml
  steering/README.md
Labels: size/S

#1370 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1373 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1374 requesting org access for James McShane, user: jmcshane
  org/members.yaml
Labels: size/XS, ok-to-test

#1375 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/M, auto-merge, release-notes-none

#1376 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1377 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1378 Remove istio community discussion board reference
  .github/pull_request_template.md
Labels: size/XS

#1379 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/M, auto-merge, release-notes-none

#1380 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1381 Change John's affiliation
  TECH-OVERSIGHT-COMMITTEE.md
  WORKING-GROUPS.md
Labels: size/XS

#1383 org: nominate bleggett as Ztunnel maintainer
  org/teams.yaml
Labels: size/XS, release-notes-none

#1384 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1385 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1386 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1387 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1388 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
