Repository istio/community, pull requests merged in 2024-01, with the labels that each got.

#1288 Update support ticket link
  CLA.md
Labels: size/S

#1287 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1289 add member: YaoZengzeng to community members
  org/members.yaml
Labels: size/XS, ok-to-test

#1290 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1293 Update members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#1294 Add 1.21 release managers
  org/members.yaml
  org/teams.yaml
Labels: size/XS

#1295 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1297 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1298 add member: LZiHaN to community members
  org/members.yaml
Labels: size/XS, ok-to-test

#1300 Update WORKING-GROUPS.md
  WORKING-GROUPS.md
Labels: size/XS

#1303 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1304 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1305 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1306 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1307 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1308 Update WORKING-GROUPS.md
  WORKING-GROUPS.md
Labels: size/XS

#1309 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1310 Update WORKING-GROUPS.md
  WORKING-GROUPS.md
Labels: size/S

#1312 add member: joaopgrassi to community members
  org/members.yaml
Labels: size/XS, ok-to-test

#1313 Add Daniel Hawton to BTR
  org/teams.yaml
Labels: size/XS

#1317 org: remove config maintainer group
  org/teams.yaml
Labels: size/XS

#1318 org: move out old release manager groups
  org/emeritus.yaml
  org/teams.yaml
Labels: size/L

#1321 org: add test emeritus is well formed
  go.mod
  go.sum
  org/config_test.go
Labels: size/S

#1323 Update teams.yaml to add Ben to networking maintainer
  org/teams.yaml
Labels: size/XS

#1324 Automator: update common-files@master in istio/community@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
