Repository istio/community, pull requests merged in 2024-02, with the labels that each got.

#1325 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1326 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1327 add member: delavet to community members
  org/members.yaml
Labels: size/XS, ok-to-test

#1329 add member: osswangxining to community members
  org/members.yaml
Labels: size/XS, ok-to-test

#1331 Added myself to istio members
  org/members.yaml
Labels: size/XS, ok-to-test

#1333 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1322 org: Transition inactive maintainers to Emeritus
  org/emeritus.yaml
  org/teams.yaml
Labels: size/M

#1332 Add hanxiaop to networking maintainers
  org/teams.yaml
Labels: size/XS

#1334 Revert "add member: osswangxining to community members"
  org/members.yaml
Labels: size/XS

#1335 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1336 Automator: update common-files@master in istio/community@master
  SUPPORT.md
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1337 Finish removing google-admin
  org/members.yaml
Labels: size/XS

#1338 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#1339 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#1340 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#1341 Member update
  org/members.yaml
  org/teams.yaml
  steering/README.md
Labels: size/M

#1342 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1343 Add `saiskee` to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1345 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1346 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1347 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb-native.yaml
Labels: size/L, auto-merge, release-notes-none

#1348 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1349 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1344 Change the Istio Steering Committee charter to align Community Seat elections and Contribution Seat allocation.
  steering/CHARTER.md
Labels: size/M
