Repository istio/community, pull requests merged in 2024-11, with the labels that each got.

#1497 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1498 add rsalmond
  org/members.yaml
Labels: size/XS, ok-to-test

#1499 add MaYuan-02 into members
  org/members.yaml
Labels: size/XS, ok-to-test

#1500 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1488 Add bleggett to docs/infra group
  org/teams.yaml
Labels: size/XS

#1501 add Louis Ryan to steering
  steering/README.md
Labels: size/XS

#1502 add Louis Ryan to steering team
  org/teams.yaml
Labels: size/XS

#1503 Adding Adarsh to members
  org/members.yaml
Labels: size/XS, ok-to-test

#1504 update steering
  steering/README.md
Labels: size/XS

#1505 Add Andygol to members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#1507 request membership for kanurag94
  org/members.yaml
Labels: size/XS, ok-to-test

#1510 maintainers: nominate Keith as a pilot maintainer
  org/teams.yaml
Labels: size/XS

#1509 Add RMs for 1.25
  org/teams.yaml
Labels: size/XS

#1513 Update WORKING-GROUPS.md
  WORKING-GROUPS.md
Labels: size/XS

#1514 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1515 Fix indentation of TOC criteria
  TECH-OVERSIGHT-COMMITTEE.md
Labels: size/XS

#1516 WORKING-GROUPS.md: Add Jackie Maertens (Elliott) to PSWG.
  WORKING-GROUPS.md
Labels: size/XS
