Repository istio/community, pull requests merged in 2024-07, with the labels that each got.

#1427 Add sridhargaddam to community members
  org/members.yaml
Labels: size/XS, ok-to-test

#1428 Add ericdbishop to the Istio org
  org/members.yaml
Labels: size/XS, ok-to-test

#1429 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1430 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1431 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1432 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1438 fix postjob
  org/members.yaml
Labels: size/XS

#1439 Add dio to the Istio org
  org/members.yaml
Labels: size/XS, ok-to-test

#1437 Add Release managers for 1.23
  org/teams.yaml
Labels: size/XS

#1436 Update community links
  ADMINS-FOR-ISTIO.md
  CONTRIBUTING.md
  README.md
  ROLES.md
  TECH-OVERSIGHT-COMMITTEE.md
  WORKING-GROUP-PROCESSES.md
  WORKING-GROUPS.md
  steering/elections/2022/candidate-craigbox.md
Labels: size/M

#1441 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1443 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1442 Add keithmattix as a Policies and Telemetry maintainer
  org/teams.yaml
Labels: size/XS

#1444 Update ADMINS-FOR-ISTIO.md
  ADMINS-FOR-ISTIO.md
Labels: size/XS

#1445 Automator: update common-files@master in istio/community@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1446 Update Microsoft’s Disclosure email
  EARLY-DISCLOSURE.md
Labels: size/XS

#1447 Update ADMINS-FOR-ISTIO.md
  ADMINS-FOR-ISTIO.md
Labels: size/XS

#1448 Update README.md on steering member
  steering/README.md
Labels: size/XS

#1449 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1450 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
