Repository istio/community, pull requests merged in 2025-04, with the labels that each got.

#1592 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1594 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1595 fix lint
  org/config_test.go
Labels: size/S

#1596 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/format_go.sh
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/XL, auto-merge, release-notes-none

#1597 add 1.26 release managers
  org/teams.yaml
Labels: size/XS

#1598 Update members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#1599 Adding tertiary to RM 1.26
  org/members.yaml
  org/teams.yaml
Labels: size/XS, ok-to-test

#1601 Add Faseela K to Operation Maintainers WG
  org/teams.yaml
Labels: size/XS

#1602 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1603 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1604 EARLY-DISCLOSURE.md: Remove F5
  EARLY-DISCLOSURE.md
Labels: size/XS
