Repository istio/community, pull requests merged in 2025-07, with the labels that each got.

#1635 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1638 ctartici member request
  org/members.yaml
Labels: size/XS, ok-to-test

#1639 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1634 Add steven as maintainer for UX
  org/teams.yaml
Labels: size/XS

#1643 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1644 Update members in org
  org/members.yaml
Labels: size/XS, ok-to-test

#1646 Update members in the org
  org/members.yaml
Labels: size/XS, ok-to-test

#1648 add cam-garrison to org members
  org/members.yaml
Labels: size/XS, ok-to-test
