Repository istio/community, pull requests merged in 2025-05, with the labels that each got.

#1606 Update maintainers
  org/emeritus.yaml
  org/teams.yaml
Labels: size/M

#1605 add me to env maintainers
  org/teams.yaml
Labels: size/XS

#1607 add kevin-shelaga as an org member
  org/members.yaml
Labels: size/XS, ok-to-test

#1608 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1610 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1611 Update members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#1613 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1614 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1615 Correct my teams membership
  org/teams.yaml
Labels: size/XS

#1616 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1617 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1618 Update members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#1619 Update teams.yaml
  org/teams.yaml
Labels: size/XS
