Repository istio/community, pull requests merged in 2025-02, with the labels that each got.

#1530 org: Transition inactive maintainers to Emeritus (2024)
  org/emeritus.yaml
  org/teams.yaml
Labels: size/S

#1553 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1554 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1555 remove 1.22 RMs
  org/teams.yaml
Labels: size/XS

#1556 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1558 add YanyChoi as member
  org/members.yaml
Labels: size/XS, ok-to-test

#1557 set up 2025 election
  steering/elections/2025/README.md
  steering/elections/2025/election.yaml
  steering/elections/2025/election_desc.md
  steering/elections/2025/nomination-template.md
  steering/elections/2025/voters.yaml
Labels: size/L

#1559 Update Elections README.md
  steering/elections/README.md
Labels: size/XS

#1560 Update election README.md
  steering/README.md
Labels: size/XS

#1561 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1562 Add Steering nomination - kfaseela
  steering/elections/2025/candidate-kfaseela.md
Labels: size/S

#1564 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1566 nomination for rcernich
  steering/elections/2025/candidate-rcernich.md
Labels: size/M

#1567 Add Steering nomination - Wilson Wu
  steering/elections/2025/candidate-wilsonwu.md
Labels: size/S

#1568 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1569 extend Steering election by 1 week
  steering/elections/2025/README.md
  steering/elections/2025/election.yaml
Labels: size/S

#1571 add dependabot to members
  org/members.yaml
Labels: size/XS

#1572 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1573 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
