Repository istio/community, pull requests merged in 2025-01, with the labels that each got.

#1533 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1536 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1537 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#1539 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#1541 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1542 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1543 add Sanchit-20 to org member
  org/members.yaml
Labels: size/XS, ok-to-test

#1544 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1545 Add Winbobob to member list
  org/members.yaml
Labels: size/XS, ok-to-test

#1546 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1547 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1549 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1550 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1552 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none
