Repository istio/community, pull requests merged in 2025-03, with the labels that each got.

#1575 nominate Pratima Nambiar to Steering
  steering/elections/2025/candidate-pnambiarsf.md
Labels: size/S

#1576 add 2025 Steering members
  steering/CONTRIBUTION-FORMULA.md
  steering/README.md
Labels: size/M

#1577 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#1578 Automator: update common-files@master in istio/community@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1579 conradhanson requesting org membership
  org/members.yaml
Labels: size/XS, ok-to-test

#1580 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1581 Move @bleggett to emeritus maintainer
  org/emeritus.yaml
  org/teams.yaml
Labels: size/XS

#1582 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1584 Align github steering group with current steering members
  org/members.yaml
  org/teams.yaml
Labels: size/S, release-notes-none

#1583 Add TOC to repo admins
  org/teams.yaml
Labels: size/XS

#1585 Update members.yaml
  org/members.yaml
Labels: size/XS

#1586 add LiorLieberman to istio members
  org/members.yaml
Labels: size/XS, ok-to-test

#1587 Add Ted Poole as a member
  org/members.yaml
Labels: size/XS, ok-to-test

#1588 Automator: update common-files@master in istio/community@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1589 Update members.yaml
  org/members.yaml
Labels: size/XS, ok-to-test

#1590 Requesting org membership for Harsh Pratap Singh, user: harsh-ps-2003
  org/members.yaml
Labels: size/XS, ok-to-test
